#ifndef MIDI_PARSERSYNTHESIZER_ADRENVELOPESTATE_H
#define MIDI_PARSERSYNTHESIZER_ADRENVELOPESTATE_H

enum ADREnvelopeState {
    IDLE,
    ATTACK,
    DECAY,
    RELEASE
};

#endif //MIDI_PARSERSYNTHESIZER_ADRENVELOPESTATE_H