#ifndef MIDI_PARSERSYNTHESIZER_ENVELOPESTATE_H
#define MIDI_PARSERSYNTHESIZER_ENVELOPESTATE_H

enum class ADSREnvelopeState {
    IDLE,
    ATTACK,
    DECAY,
    SUSTAIN,
    RELEASE
};

#endif //MIDI_PARSERSYNTHESIZER_ENVELOPESTATE_H