#ifndef MIDI_PARSERSYNTHESIZER_ENVELOPESTATE_H
#define MIDI_PARSERSYNTHESIZER_ENVELOPESTATE_H

enum EnvelopeState {
    IDLE,
    ATTACK,
    DECAY,
    SUSTAIN,
    RELEASE
};

#endif //MIDI_PARSERSYNTHESIZER_ENVELOPESTATE_H