#ifndef MIDI_PARSERSYNTHESIZER_CONTINUOUSCONTROLLERS_H
#define MIDI_PARSERSYNTHESIZER_CONTINUOUSCONTROLLERS_H

enum ContinuousController {
    SUSTAIN_PEDAL = 64,
    MODULATION_WHEEL = 1,
    CHANNEL_VOLUME = 7,
    EXPRESSION = 11,
    ALL_SOUND_OFF = 120,
    RESET_ALL_CONTROLLERS = 121,
    ALL_NOTES_OFF = 123
};

#endif //MIDI_PARSERSYNTHESIZER_CONTINUOUSCONTROLLERS_H