#ifndef MIDI_PARSERSYNTHESIZER_METAEVENTTYPE_H
#define MIDI_PARSERSYNTHESIZER_METAEVENTTYPE_H

enum MetaEventType {
    SEQUENCE_NUMBER = 0x00,
    TEXT_EVENT = 0x01,
    COPYRIGHT_NOTICE = 0x02,
    SEQUENCE_TRACK_NAME = 0x03,
    INSTRUMENT_NAME = 0x04,
    LYRIC_TEXT = 0x05,
    MARKER_TEXT = 0x06,
    CUE_POINT = 0x07,
    MIDI_CHANNEL_PREFIX = 0x20,
    END_OF_TRACK = 0x2F,
    TEMPO_SETTING = 0x51,
    SMPTE_OFFSET = 0x54,
    TIME_SIGNATURE = 0x58,
    KEY_SIGNATURE = 0x59,
    SEQUENCE_SPECIFIC_META_EVENT = 0x7F
};

#endif // MIDI_PARSERSYNTHESIZER_METAEVENTTYPE_H