//
// Created by williamh on 4/7/26.
//

#ifndef MIDI_PARSERSYNTHESIZER_MIDIEVENTTYPE_H
#define MIDI_PARSERSYNTHESIZER_MIDIEVENTTYPE_H

enum MidiEventType {
    NOTE_ON = 0x90,
    NOTE_OFF = 0x80,
    CONTROL_CHANGE = 0xB0,
    PROGRAM_CHANGE = 0xC0,
    CHANNEL_PRESSURE = 0xD0,
    PITCH_BEND = 0xE0
};

#endif //MIDI_PARSERSYNTHESIZER_MIDIEVENTTYPE_H